## Workaround KSCrash static linking issue
# https://github.com/kstenerud/KSCrash/issues/713
use_modular_headers!
#

# The podspecs in this fork are named `Flashcat*`; each keeps `module_name = Datadog*`, so the
# scenarios still `import DatadogCore` and friends. Asking for the old pod names here left
# `pod install` reporting "No podspec found", which took the whole UI test suite with it.

target 'Runner iOS' do
    platform :ios, '12.0'

    pod 'FlashcatCore', :path => '..'
    pod 'FlashcatLogs', :path => '..'
    pod 'FlashcatTrace', :path => '..'
    pod 'FlashcatRUM', :path => '..'
    pod 'FlashcatCrashReporting', :path => '..'
    pod 'FlashcatSessionReplay', :path => '..'
    pod 'FlashcatWebViewTracking', :path => '..'

    target 'IntegrationScenarios' do
        pod 'FlashcatInternal', :path => '..'
        pod 'FlashcatTestUtilities', :path => '..'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) DD_SDK_ENABLE_EXPERIMENTAL_APIS DD_SDK_COMPILED_FOR_TESTING'
        end
    end
end
